import "@/app/globals.css";
import Header from "@/components/Layout/Header";
import Sidebar from "@/components/Layout/Sidebar";
import Providers from "@/components/Providers";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  authModal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <div className="flex flex-col relative  antialiased min-h-screen">
          <Header />
          <div className="flex-1 flex " style={{backgroundImage: 'url(/)'}}>
            <Sidebar />
            <main className="flex-1">{children}</main>
          </div>
        </div>
        <Toaster />
        <Sonner />
      </Providers>
    </html>
  );
}
