-- CreateEnum
CREATE TYPE "Category" AS ENUM ('SCIENCE', 'MATH', 'HISTORY', 'GEOGRAPHY', 'LITERATURE', 'TECHNOLOGY', 'SPORTS', 'ART', 'LANGUAGE', 'GENERAL_KNOWLEDGE', 'POLITICS', 'ECONOMICS', 'PHILOSOPHY', 'PSYCHOLOGY', 'BIOLOGY', 'CHEMISTRY', 'PHYSICS', 'COMPUTER_SCIENCE', 'RELIGION', 'NATURE', 'EDUCATION');

-- AlterTable
ALTER TABLE "Question" ADD COLUMN     "categories" "Category"[];
